services:
  api:
    build: .
    container_name: batuta-api
    restart: unless-stopped

    env_file:
      - .env.production

    environment:
      NODE_ENV: production

    ports:
      - "3000:3000"